### ISSUE TITLE
No predefined types for the introduces options.

### ISSUE THREAD

**Issue by teodorescuserban** [manwaring/serverless-prune-versions#16]
```
CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
   - PrunePlugin for "number", "stage", "region", "function", "layer", "includeLayers", "dryRun"
  
  Please report this issue in plugin issue tracker.
```

**Comment by charithar** [comment]
Got the same feedback from the serverless today when using this plugin. Serverless doctor also reported following.

Starting with next major release, this will be communicated with a thrown error.
More info: https://serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA_V3

**Comment by teodorescuserban** [comment]
Sorry, just went with `serverless-prune-plugin` instead.
